# Generated by Django 5.0 on 2024-01-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='age_name',
            new_name='age',
        ),
    ]
