# Generated by Django 5.0 on 2024-01-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_age_name_leads_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leads',
            new_name='Lead',
        ),
    ]
